config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users, controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }

  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }

  resources :posts
  resources :comments, only: %i(create edit update destroy)
end

app/models/ability/admin_ability.rb
module Ability
  class AdminAbility
    include CanCan::Ability

    def initialize(admin)
      if admin
        # ability for admin
        can :manage, Post
      end
    end
  end
end

app/models/ability/user_ability.rb
module Ability
  class UserAbility
    include CanCan::Ability

    def initialize(user)
      # ability for all user (even not logged in)
      can :read, Post

      if user
        # ability for logged in usser
        can :manage, Post, user_id: user.id
        can :create, Comment
        can [:update, :destroy], Comment, user_id: user.id
        can :destroy, Comment, post: { user_id: user.id }

        # ability for admin usser
        if user.is_admin?
          can :manage, Post
          can [:update, :destroy], Comment
        end
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :recoverable, :rememberable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :recoverable, :rememberable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :password_confirmation, presence: true, if: :password
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied, with: :cancan_access_denied

  private

  def cancan_access_denied exception
    flash[:warning] = exception.message
    redirect_to root_url
  end

  def current_ability
    @current_ability ||= if current_admin
      Ability::AdminAbility.new(current_admin)
    else
      Ability::UserAbility.new(current_user)
    end
  end

  def authenticate_user!
    return super if current_user
    authenticate_admin!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i(create edit update)
  load_and_authorize_resource

  def create
    @comment = Comment.create comment_params.merge user: current_user
  end

  def edit
  end

  def update
    @comment.update_attributes comment_params
  end

  def destroy
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit :body, :post_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i(edit update destroy)
  before_action :load_post, only: %i(show edit update destroy)
  # before_action :authorize_by_cancan, only: %i(edit update destroy)
  load_and_authorize_resource

  def index
    @posts = Post.includes(:user, :comments).order(created_at: :desc).page(params[:page]).per 5
  end

  def new
  end

  def create
    @post = Post.create post_params.merge(user: current_user)

    if @post.valid?
      flash[:success] = "Create post success"
      redirect_to @post
    else
      flash[:danger] = "Create post fail"
      render :new
    end
  end

  def show
    @comments = @post.comments.includes(:user).order(created_at: :desc).page(params[:page]).per 3
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @post.update_attributes post_params
      flash[:success] = "Update post success"
      redirect_to @post
    else
      flash[:danger] = "Update post fail"
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Delele post success"
      redirect_to root_url
    else
      flash[:danger] = "Delele post fail"
      redirect_to @post
    end
  end

  private

  def load_post
    return if @post = Post.find_by(id: params[:id])
     
    flash[:warning] = "Post not found"
    redirect_to root_url
  end

  def post_params
    params.require(:post).permit :title, :body
  end

  # def authorize_by_cancan
  #   authorize! :manage, @post
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class type
    case type
    when "alert"
      "alert-danger"
    when "notice"
      "alert-success"
    else
      "alert-#{type}"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.valid? %>
  $('.js-comment-body').val('');
  $('.js-comment-error').text('');

  var comment = '<%= j (render "posts/comment", comment: @comment).html_safe %>';
  $('.js-comments').prepend(comment);
<% else %>
  var error = '<%= j (@comment.errors.full_messages.first).html_safe %>';
  $('.js-comment-error').text(error);
<% end %>

app/views/comments/destroy.js.erb
$('.js-comment[data-comment-id="'+ '<%= @comment.id %>' +'"]').remove();

app/views/comments/edit.js.erb
var form = '<%= j (render "posts/form_comment", comment: @comment, post: @comment.post).html_safe %>';
$('.js-comment[data-comment-id="'+ '<%= @comment.id %>' +'"]').html(form);

app/views/comments/update.js.erb
<% if @comment.valid? %>
  var comment = '<%= j (render "posts/comment", comment: @comment).html_safe %>';
  $('.js-comment[data-comment-id="'+ '<%= @comment.id %>' +'"]').html(comment);
<% else %>
  var error = '<%= j (@comment.errors.full_messages.first).html_safe %>'
  $('.js-comment[data-comment-id="'+ '<%= @comment.id %>' +'"]').find('.js-comment-error').text(error);
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class type %> alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong><%= type.capitalize %>!</strong> <%= message %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <span class="navbar-brand">
        CanCanCan
      </span>
    </div>
    <ul class="nav navbar-nav">
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <% if can? :manage, Post %>
        <li>
          <%= link_to "Create post", new_post_path %>
        </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to "#" do %>
            <span class="glyphicon glyphicon-user"></span> <%= current_user.name %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out"></span> Logout
          <% end %>
        </li>
      <% elsif admin_signed_in? %>
        <li>
          <%= link_to "#" do %>
            <span class="glyphicon glyphicon-user"></span> <%= current_admin.name %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_admin_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out"></span> Logout
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_user_registration_path do %>
            <span class="glyphicon glyphicon-user"></span> Signup
          <% end %>
        </li>
        <li>
          <%= link_to user_session_path do %>
            <span class="glyphicon glyphicon-log-in"></span> Login
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoCancancan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>

    <%= yield %>
  </body>
</html>

app/views/posts/_comment.html.erb
<div class="js-comment" data-comment-id="<%= comment.id %>">
  <div class="panel panel-default">
    <div class="panel-heading">
      Commented by <%= link_to comment.user.name, "#" %>
    </div>
    <div class="panel-body">
      <%= comment.body %>
    </div>
    <% if can?(:update, comment) || can?(:destroy, comment) %>
      <div class="panel-footer">
        <% if can?(:update, comment) %>
          <%= link_to "Update Comment", edit_comment_path(comment), remote: true %>
        <% end %>
        <% if can?(:update, comment) && can?(:destroy, comment) %>
          |
        <% end %>
        <% if can?(:destroy, comment) %>
          <%= link_to "Delete comment", comment_path(comment), method: :delete, remote: true %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for post, html: {class: "form-horizontal"} do |f| %>
  <%= render "shared/error_messages", resource: post if post.errors.any? %>

  <div class="form-group">
    <%= f.label :title, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control", autofocus: true, autocomplete: "title" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :body, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control", rows: 25, autofocus: true, autocomplete: "body" %>
    </div>
  </div>

  <div class="form-group">        
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/posts/_form_comment.html.erb
<%= form_for comment, remote: true do |f| %>
  <div class="form-group">
    <%= f.text_area :body, class: "form-control js-comment-body", rows: 5, placeholder: "Enter your comment ..." %>
    <%= f.hidden_field :post_id, value: post.id %>
    <p class="text-danger js-comment-error"></p>
  </div>
  <%= f.submit comment.persisted? ? "Update Comment" : "Comment" , class: "btn btn-default" %>
<% end %><br>

app/views/posts/_post.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Post <%= post.title %><br>
    <small>by <%= link_to post.user.name, "#" %></small>
  </div>
  <div class="panel-body">
    <%= post.body.first(400) + " ..." %> <%= link_to "Readmore with #{post.comments.size} comments", post %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h2>Update post</h2>

  <%= form_for @post, html: {class: "form-horizontal"} do |f| %>
    <%= render "shared/error_messages", resource: @post if @post.errors.any? %>

    <div class="form-group">
      <%= f.label :title, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control", autofocus: true, autocomplete: "title" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :body, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_area :body, class: "form-control", rows: 25, autofocus: true, autocomplete: "body" %>
      </div>
    </div>

    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Update", class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h2>Posts</h2>

  <%= render partial: "posts/post", collection: @posts %>

  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h2>Create post</h2>

  <%= render "posts/form", post: @post %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h2>Post <%= @post.title %></h2>
  <div>by <%= link_to @post.user.name, "#" %></div><br><br>

  <div class="panel panel-default">
    <div class="panel-body">
      <%= @post.body %>
    </div>
    <% if can? :manage, @post %>
      <div class="panel-footer">
        <%= link_to "Update post", edit_post_path(@post) %> | <%= link_to "Delete post", post_path(@post), method: :delete %>
      </div>
    <% end %>
  </div>

  <h3>Comments</h3>
  
  <%= render "posts/form_comment", comment: @comment, post: @post if can?(:create, Comment) %>

  <div class="js-comments">
    <%= render partial: "posts/comment", collection: @comments %>
  </div>

  <%= paginate @comments %>
</div>

app/views/shared/_error_messages.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">
    <%= I18n.t("errors.messages.not_saved",
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)
    %>
  </div>
  <div class="panel-body">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
</div>